import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/opt/homebrew/bin/fish"

[env]
SHELL = "/opt/homebrew/bin/fish"
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[font]
size = 16

[font.bold]
family = "DroidSansM Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "DroidSansM Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "DroidSansM Nerd Font Propo"
style = "Italic"

[font.normal]
family = "DroidSansM Nerd Font Propo"
style = "Regular"
