#!/bin/bash

echo "These will be the changes:"
echo
DIFF="$(colordiff ~/.aliases .aliases)"
echo "${DIFF}"
DIFF="$(colordiff ~/.vimrc .vimrc)"
echo "${DIFF}"
echo

echo "Are you sure you want to overwrite your dotfiles? [y/n]: "
read Answer;
if [ $Answer = 'y' ]
then
  cp .vimrc ~/.vimrc
  cp .aliases ~/.aliases
  echo;
  echo "Exported vimrc and aliases to home directory."
else
  echo;
  echo "Sure, if you say so!";
fi
