add_newline = false

aws.disabled = true
gcloud.disabled = true
golang.disabled = true
line_break.disabled = true
nodejs.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
