add_newline = false

# It can take a while to find the number of lines in the git diff for large changes
command_timeout = 1000

aws.disabled = true
c.disabled = true
docker_context.disabled = true
gcloud.disabled = true
golang.disabled = true
haskell.disabled = true
line_break.disabled = true
lua.disabled = true
nodejs.disabled = true
package.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
zig.disabled = true

[cmd_duration]
style = "bold purple"

[git_branch]
style = "bold white"

[git_status]
ahead = "[⇡](bold purple)"
behind = "[⇣](bold purple)"
diverged = "[⇕](bold purple)"
modified = "[!](bold yellow)"
stashed = "[\\$](bold red)"
staged = "[+](bold green)"
renamed = "[»](bold blue)"
deleted = "[✘](bold red)"
untracked = "[?](bold yellow)"
style = "grey"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[hostname]
ssh_symbol = ""
