set nocompatible " We're running Vim, not Vi!

""""" GENERAL

syntax on
set number
set ruler
set encoding=utf-8
set mouse=a     " Allow scrolling and pane selection in all modes
set backspace=2 " Allow backspace over indent, eol, start
set hidden      " Modified buffers are 'hidden' instead of unloaded

filetype on
filetype indent on
filetype plugin on

let mapleader=","

""""" INDENTATION

set tabstop=2      " Width of TAB character
set softtabstop=2  " Width of <TAB> key
set shiftwidth=2   " Width for formatting (>, =)
set expandtab      " Convert tabs to spaces
set smarttab       " Use shiftwidth when inserting a tab in front of a line
set shiftround     " Round indent to multiple of shiftwidth

""""" APPEARANCE

set t_Co=256
colorscheme jellybeans

set noshowmode  " Don't show mode in status bar, as Airline does it
set laststatus=2
let g:airline_theme='murmur'
let g:airline#extensions#hunks#enabled=0
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline_powerline_fonts = 1

""""" SEARCH

set hlsearch "highlight searches

" Ignores case unless search has uppercase chars
set ignorecase
set smartcase

""""" FOLDING

" Toggle fold
nnoremap <Space> za

set foldmethod=indent
set foldlevelstart=99 " Unfold everything when opening file

""""" MISCELLANEOUS MAPPINGS

" Uppercase word
nnoremap <leader>u gUiw

" Move lines up/down
nnoremap <C-J> ddp
nnoremap <C-K> kddpk

" Cycle though buffers
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bprev<CR>

nnoremap <CR> o<Esc>
nnoremap <C-G> :FZF<CR>

""""" PLUGINS

call plug#begin('~/.vim/plugged')

Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'wikitopian/hardmode'
Plug 'leafgarland/typescript-vim'
Plug 'scrooloose/nerdtree'
Plug 'gregsexton/MatchTag'
Plug 'jimenezrick/vimerl'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'airblade/vim-gitgutter'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'christoomey/vim-tmux-runner'
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-endwise'
Plug 'vim-syntastic/syntastic'
Plug 'rking/ag.vim'
Plug 'tpope/vim-commentary'

call plug#end()

""""" SYNTASTIC

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
