#!/usr/bin/env ruby

CONFIG = {
  "alacritty" => "$HOME/.config/alacritty/alacritty.toml",
  "fish" => "$HOME/.config/fish/config.fish",
  "nvim" => "$HOME/.config/nvim/init.lua",
  "starship" => "$DOTFILES/starship.toml",
  "tmux" => "$HOME/.tmux.conf",
}

arg = ARGV[0] || ""
candidates = CONFIG.keys.select { |c| c.start_with?(arg) }

selected = case candidates.size
           when 0
             puts "Invalid arg: #{arg}"
             puts "Supported configs: #{CONFIG.keys.join(', ')}"
             exit 1
           when 1
             candidates.first
           else
             `gum filter --placeholder="Which config?" --reverse #{candidates.join(" ")}`.chomp
           end

exec("$EDITOR #{CONFIG.fetch(selected)}")
