#!/usr/bin/env ruby

CONFIG = {
  "alacritty" => "$HOME/.config/alacritty/alacritty.toml",
  "fish" => "$HOME/.config/fish/config.fish",
  "nvim" => "$HOME/.config/nvim/init.lua",
  "starship" => "$DOTFILES/starship.toml",
  "tmux" => "$HOME/.tmux.conf",
}

arg = if ARGV.length.zero?
        `gum filter --placeholder="Which config?" --reverse #{CONFIG.keys.join(" ")}`.chomp
      else
        ARGV[0]
      end

cfg = CONFIG.fetch(arg) do
  puts "Invalid arg: #{arg}"
  puts "Supported configs: #{CONFIG.keys.join(', ')}"
  exit 1
end

exec("$EDITOR #{cfg}")
