#!/usr/bin/env lua

local CONFIG = {
	alacritty = "$HOME/.config/alacritty/alacritty.toml",
	fish = "$HOME/.config/fish/config.fish",
	nvim = "$HOME/.config/nvim/init.lua",
	starship = "$DOTFILES/starship.toml",
	tmux = "$HOME/.tmux.conf",
}

local isPrefix = function(prefix, str)
	return string.sub(str, 1, #prefix) == prefix
end

local a = arg[1] or ""

local candidates = {}
for k in pairs(CONFIG) do
	if isPrefix(a, k) then
		table.insert(candidates, k)
	end
end

if #candidates == 0 then
	print("Invalid")
	os.exit(1)
elseif #candidates == 1 then
	print("Found: " .. candidates[1])
else
	print("Found many:")
	for k, v in pairs(candidates) do
		print(k, v)
	end
	os.exit(1)
end

os.execute("$EDITOR " .. CONFIG[candidates[1]])
