#!/usr/bin/env ruby

if ARGV.length != 1
  puts "Usage: #{File.basename(__FILE__)} <foo>/<bar>"
  exit 1
end

arg = ARGV.first
# Normalize to org/repo form, e.g. ameykusurkar/dotfiles
# Accepts: ameykusurkar/dotfiles
#          https://github.com/ameykusurkar/dotfiles
#          https://github.com/ameykusurkar/dotfiles?tab=readme-ov-file
arg = arg.sub(/\?.*/, '').sub(%r{^https?://github\.com/}, '').chomp('/')
parts = arg.split('/')

if parts.size != 2 || parts.first.nil?
  puts "Usage: #{File.basename(__FILE__)} <foo>/<bar>"
  exit 1
end

if parts[0] == "intercom"
  `git clone git@github.com:#{arg}.git ~/src/#{parts[1]}`
else
  `git clone git@github.com:#{arg}.git ~/projects/#{arg}`
end
