#!/bin/zsh
alias sshdoc="ssh avk13@shell2.doc.ic.ac.uk"
alias sicstus="rlwrap /usr/local/sicstus4.3.2/bin/sicstus"
alias localip='ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '\''{print $2}'\'''
alias als="vim ~/.aliases"
alias vimrc="vim ~/.vimrc"
alias zshrc="vim ~/.zshrc"
alias penv="vim ~/.private-env"
alias grbim="git rebase -i master"

# Get battery % on mac
alias batt='pmset -g batt'

# Find alias commands
function algrep() {
  alias | grep $@
}

# Prompts with the files you are trying to delete
function rmc() {
  ls $@;
  if [ $# = 0 ]
  then
    echo "\nWarning: You are trying to delete everything in the current directory."
  fi
  echo "\nDo you want to delete these files? [y/n]: ";
  read Answer;
  if [ $Answer = 'y' ]
  then
    rm -rf $@;
    echo "\nIt's all gone.";
  else
    echo "\nPhew, good decision.";
  fi
}

# A simple `watch` function, but with colour
function watch2() {
  while true; do
    clear
    eval $1
    sleep 2
  done
}

# Recursively finds the number of files in $1
function nfiles() {
  find $1 -type f | wc -l
}
