#!/bin/zsh
alias sicstus="rlwrap /usr/local/sicstus4.3.2/bin/sicstus"
alias localip='ipconfig getifaddr en0'
alias als="vim ~/.aliases"
alias vimrc="vim ~/.vimrc"
alias zshrc="vim ~/.zshrc"
alias penv="vim ~/.private-env"
alias sz="source ~/.zshrc"
alias rmswap="rmc ./**/.*.sw*"
alias bell="echo \"\a\""
alias crr="cargo run --release"

alias grbim='git rebase -i $(git_main_branch)'
alias gcaa="git commit -a --amend"

# Get battery % on mac
alias batt='pmset -g batt'

# Copy a file to clipboard
function copy() {
  cat $@ | pbcopy
}

# Find alias commands
function algrep() {
  alias | grep $@
}

# Prompts with the files you are trying to delete
function rmc() {
  ls $@;
  if [ $# = 0 ]
  then
    echo "\nWarning: You are trying to delete everything in the current directory."
  fi
  echo "\nDo you want to delete these files? [y/n]: ";
  read Answer;
  if [ $Answer = 'y' ]
  then
    rm -rf $@;
    echo "\nIt's all gone.";
  else
    echo "\nPhew, good decision.";
  fi
}

# A simple `watch` function, but with colour
function watch2() {
  while true; do
    clear
    eval $1
    sleep 2
  done
}

# Recursively finds the number of files in $1
function nfiles() {
  find $1 -type f | wc -l
}

function gclone() {
  if [ $# -eq 1 ]
  then
    git clone git@github.com:ameykusurkar/$1.git
  else
    git clone git@github.com:$1/$2.git
  fi
}
