export DOTFILES=$HOME/dotfiles
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$DOTFILES/zsh/zsh_custom
export EDITOR='vim'
export VISUAL='vim'
export GOPATH=$(go env GOPATH)

PATH=""
PATH="$PATH:/usr/local/bin"
PATH="$PATH:/usr/bin"
PATH="$PATH:/bin"
PATH="$PATH:/usr/sbin"
PATH="$PATH:/sbin"
PATH="$PATH:$HOME/.cargo/bin"
PATH="$PATH:$HOME/.local/bin"
PATH="$PATH:$GOPATH/bin"
export PATH

##### THEME #####

ZSH_THEME="bullet-train"

BULLETTRAIN_PROMPT_ORDER=(status dir git cmd_exec_time)
BULLETTRAIN_PROMPT_SEPARATE_LINE=false
BULLETTRAIN_GIT_COLORIZE_DIRTY=true
BULLETTRAIN_PROMPT_CHAR=''
BULLETTRAIN_EXEC_TIME_BG=white
BULLETTRAIN_EXEC_TIME_FG=black

#################

plugins=(git zsh-syntax-highlighting)

ZSH_DISABLE_COMPFIX=true

source $ZSH/oh-my-zsh.sh

source ~/.aliases

# Machine-specific config
[ -f ~/.private-env ] && source ~/.private-env

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# nvm setup
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

. /usr/local/opt/asdf/asdf.sh
export PATH="/usr/local/opt/openjdk/bin:$PATH"

export PATH="$HOME/.poetry/bin:$PATH"
[ -f "/Users/ameykusurkar/.ghcup/env" ] && source "/Users/ameykusurkar/.ghcup/env" # ghcup-env
