export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/dotfiles/zsh/zsh_custom
export EDITOR='vim'

##### THEME #####

ZSH_THEME="bullet-train"

BULLETTRAIN_TIME_SHOW=false
BULLETTRAIN_PROMPT_SEPARATE_LINE=false
BULLETTRAIN_GIT_COLORIZE_DIRTY=true
BULLETTRAIN_PROMPT_CHAR=''
BULLETTRAIN_STATUS_EXIT_SHOW=true

#################

plugins=(git zsh-syntax-highlighting)

# User configuration

export PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

source $ZSH/oh-my-zsh.sh

source ~/.aliases
[ -f ~/.private-env ] && source ~/.private-env

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
